services:
  api:
    build: .
    container_name: kiirlink-backend
    ports:
      - "80:8080"
    volumes:
      - kiirlink_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

volumes:
  kiirlink_data: